name: atomic_transact_flutter_example
description: Demonstrates how to use the atomic_transact_flutter plugin.
publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  atomic_transact_flutter:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
