version: 2
updates:
  - package-ecosystem: 'swift'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'github.com/atomicfi/atomic-transact-ios'

  - package-ecosystem: 'gradle'
    directory: '/android'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'financial.atomic:transact'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
