name: analyze

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
