name: Build

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios-spm:
    name: Build iOS (SPM)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: "stable"

      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager

      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build iOS
        working-directory: ./example
        run: flutter build ios --no-codesign

  build-ios-cocoapods:
    name: Build iOS (CocoaPods)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: "stable"

      - name: Disable Swift Package Manager
        run: flutter config --no-enable-swift-package-manager

      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build iOS
        working-directory: ./example
        run: flutter build ios --no-codesign

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: "stable"

      - name: Install dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build Android
        working-directory: ./example
        run: flutter build apk --debug
