name: publish to pub.dev

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        run: |
          NEW_VERSION="${{ github.event.release.tag_name }}"
          # Remove 'v' prefix if present
          NEW_VERSION="${NEW_VERSION#v}"
          ./scripts/bump_version.sh --version "$NEW_VERSION"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: dart pub get

      - name: Setup Pub credentials
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart
          echo '${{ secrets.PUB_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"

      - name: Publish Package
        run: dart pub publish -f
