name: security

on:
  pull_request:
    branches:
      - master
    types: [opened, ready_for_review, synchronize]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
