name: Sync Linear Release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - uses: linear/linear-release-action@af56a9a388625921f3757a2f988e4d7aca958377
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY_FLUTTER }}
          command: sync
          timeout: 120
