name: update sdk's

on:
  workflow_dispatch:

jobs:
  update-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Android SDK
        id: update-android
        run: |
          if NEW_VERSION=$(bash ./scripts/update_android_sdk.sh); then
            echo "ANDROID_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "ANDROID_BRANCH=update_android_sdk_$NEW_VERSION" >> $GITHUB_ENV
            echo "Android SDK updated to $NEW_VERSION"
          else
            echo "No Android SDK update needed or update failed"
          fi

      - name: Commit Android SDK changes
        id: commit-android
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          ANDROID_VERSION: ${{ env.ANDROID_VERSION }}
          ANDROID_BRANCH: ${{ env.ANDROID_BRANCH }}
        with:
          commit_message: "chore: updated android sdk to ${{ env.ANDROID_VERSION }}"
          file_pattern: "android/build.gradle"
          branch: ${{ env.ANDROID_BRANCH }}
          create_branch: true

      - name: Create Android SDK PR
        if: steps.commit-android.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base master \
            --head $ANDROID_BRANCH \
            --title "chore: update Android SDK to $ANDROID_VERSION" \
            --body "Automated update of Android Transact SDK to version $ANDROID_VERSION"

  update-ios:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update iOS SDK
        id: update-ios
        run: |
          if NEW_VERSION=$(bash ./scripts/update_atomic_sdk.sh); then
            echo "IOS_VERSION=$NEW_VERSION" >> $GITHUB_ENV
            echo "IOS_BRANCH=update_ios_sdk_$NEW_VERSION" >> $GITHUB_ENV
            echo "iOS SDK updated to $NEW_VERSION"
          else
            echo "No iOS SDK update needed or update failed"
          fi

      - name: Commit iOS SDK changes
        id: commit-ios
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          IOS_VERSION: ${{ env.IOS_VERSION }}
          IOS_BRANCH: ${{ env.IOS_BRANCH }}
        with:
          commit_message: "chore: updated ios sdk to ${{ env.IOS_VERSION }}"
          file_pattern: "ios/atomic_transact_flutter.podspec"
          branch: ${{ env.IOS_BRANCH }}
          create_branch: true

      - name: Create iOS SDK PR
        if: steps.commit-ios.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base master \
            --head $IOS_BRANCH \
            --title "chore: update iOS SDK to $IOS_VERSION" \
            --body "Automated update of iOS Transact SDK to version $IOS_VERSION"
